spring:
  profiles.active: development
  jpa:
    database: postgresql
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      jadira:
        usertype:
          autoRegisterUserTypes: true

---
spring:
  profiles: development
  datasource:
#     driverClassName: org.h2.Driver
#     url: jdbc:h2:~/test2;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#     username: sa
#     password:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://10.32.150.91:5432/mmjtest
    username: postgres
    password: yintai@123
